customhost = "database-1.cbyegpcunxow.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "leonardlohhanwei-employee"
customregion = "us-east-1"
